import type { Metadata } from 'next'
import {} from 'next/font/google'
import localFont from 'next/font/local'
import './globals.css'

const averta = localFont({
  src: [
    {
      path: './fonts/Intelligent Design - AvertaStdCy-Extrathin_1.otf',
      weight: '100',
      style: 'normal',
    },
    {
      path: './fonts/Intelligent Design - AvertaStdCY-Thin_1.otf',
      weight: '200',
      style: 'normal',
    },
    {
      path: './fonts/Intelligent Design - AvertaStdCY-Light_1.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/Intelligent Design - AvertaStdCY-Regular_3.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Intelligent Design - AvertaStdCY-Semibold_1.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/Intelligent Design - AvertaStdCY-Bold_1.otf',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/Intelligent Design - AvertaStdCY-Extrabold_1.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/Intelligent Design - AvertaStdCY-Black_1.otf',
      weight: '800',
      style: 'normal',
    },
  ],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${averta.className} antialiased`}>{children}</body>
    </html>
  )
}
